# Outgoing email settings

production:
  delivery_method: :smtp
  smtp_settings:
    address: "smtp.gmail.com"
    port: 587
    domain: "eneida.biz.ua"
    authentication: :login
    user_name: "project@eneida.biz.ua"
    password: "HJQqGswiPdv5VUdzQ43l"
  
development:
  delivery_method: :smtp
  smtp_settings:
    address: smtp.gmail.com
    port: 587
    domain: eneida.biz.ua
    authentication: :login
    user_name: project@eneida.biz.ua
    password: HJQqGswiPdv5VUdzQ43l
